name: front_end
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  excel: ^4.0.2

  provider: ^6.0.0
  cloud_firestore: ^4.15.4
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.1.6



  flutter_lints: ^3.0.1
  analyzer: ^5.13.0

flutter:
  uses-material-design: true